version: "3"

services:

  chain-test-1:
    image: icad:local
    command: bash /network/start.sh
    env_file: docker.env
    environment:
      CHAINID: test-1
    volumes:
      - ./storage:/home/ubuntu/data
      - ./network:/network
  
  chain-test-2:
    image: icad:local
    command: bash /network/start.sh
    env_file: docker.env
    environment:
      CHAINID: test-2
    volumes:
      - ./storage:/home/ubuntu/data
      - ./network:/network

  relayer:
    image: relayer:local
    command: bash ./network/relayer/interchain-acc-config/rly-start.sh
    volumes:
      - ./storage:/src/app/data
      - ./network:/src/app/network

  oracle:
    image: oracle:local
    command: bash /src/app/oracle/run_oracle.sh
    volumes:
      - ./storage:/src/app/data
      - ./oracle:/src/app/oracle
