version: "3"

services:

  chain-test-1:
    image: icad:local
    command: bash /network/start.sh
    environment:
      CHAINID: test-1
      GRPCPORT: 8090
      GRPCWEB: 8091
    volumes:
      - ./storage:/home/ubuntu/data
      - ./network:/network
  
  chain-test-2:
    image: icad:local
    command: bash /network/start.sh
    environment:
      CHAINID: test-2
      GRPCPORT: 8090
      GRPCWEB: 8091
    volumes:
      - ./storage:/home/ubuntu/data
      - ./network:/network

  relayer:
    image: relayer:local
    command: bash ./network/relayer/interchain-acc-config/rly-start.sh
    volumes:
      - ./storage:/src/app/data
      - ./network:/src/app/network

  controller-oracle:
    image: oracle:local
    command: bash /src/app/oracle/run_controller_oracle.sh
    volumes:
      - ./oracle:/src/app/oracle
      - ./storage/oracle/docker.env:/src/app/docker.env
  
  host-oracle:
    image: oracle:local
    command: bash /src/app/oracle/run_host_oracle.sh
    volumes:
      - ./oracle:/src/app/oracle
      - ./storage/oracle/docker.env:/src/app/docker.env
