// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchainaccounts/controller/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCmpDataRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCmpDataRequest) Reset()         { *m = QueryGetCmpDataRequest{} }
func (m *QueryGetCmpDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCmpDataRequest) ProtoMessage()    {}
func (*QueryGetCmpDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{2}
}
func (m *QueryGetCmpDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCmpDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCmpDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCmpDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCmpDataRequest.Merge(m, src)
}
func (m *QueryGetCmpDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCmpDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCmpDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCmpDataRequest proto.InternalMessageInfo

func (m *QueryGetCmpDataRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCmpDataResponse struct {
	CmpData CmpData `protobuf:"bytes,1,opt,name=cmpData,proto3" json:"cmpData"`
}

func (m *QueryGetCmpDataResponse) Reset()         { *m = QueryGetCmpDataResponse{} }
func (m *QueryGetCmpDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCmpDataResponse) ProtoMessage()    {}
func (*QueryGetCmpDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{3}
}
func (m *QueryGetCmpDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCmpDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCmpDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCmpDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCmpDataResponse.Merge(m, src)
}
func (m *QueryGetCmpDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCmpDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCmpDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCmpDataResponse proto.InternalMessageInfo

func (m *QueryGetCmpDataResponse) GetCmpData() CmpData {
	if m != nil {
		return m.CmpData
	}
	return CmpData{}
}

type QueryAllCmpDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCmpDataRequest) Reset()         { *m = QueryAllCmpDataRequest{} }
func (m *QueryAllCmpDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCmpDataRequest) ProtoMessage()    {}
func (*QueryAllCmpDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{4}
}
func (m *QueryAllCmpDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCmpDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCmpDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCmpDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCmpDataRequest.Merge(m, src)
}
func (m *QueryAllCmpDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCmpDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCmpDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCmpDataRequest proto.InternalMessageInfo

func (m *QueryAllCmpDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCmpDataResponse struct {
	CmpData    []CmpData           `protobuf:"bytes,1,rep,name=cmpData,proto3" json:"cmpData"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCmpDataResponse) Reset()         { *m = QueryAllCmpDataResponse{} }
func (m *QueryAllCmpDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCmpDataResponse) ProtoMessage()    {}
func (*QueryAllCmpDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{5}
}
func (m *QueryAllCmpDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCmpDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCmpDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCmpDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCmpDataResponse.Merge(m, src)
}
func (m *QueryAllCmpDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCmpDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCmpDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCmpDataResponse proto.InternalMessageInfo

func (m *QueryAllCmpDataResponse) GetCmpData() []CmpData {
	if m != nil {
		return m.CmpData
	}
	return nil
}

func (m *QueryAllCmpDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCmpControllerRequestRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCmpControllerRequestRequest) Reset()         { *m = QueryGetCmpControllerRequestRequest{} }
func (m *QueryGetCmpControllerRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCmpControllerRequestRequest) ProtoMessage()    {}
func (*QueryGetCmpControllerRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{6}
}
func (m *QueryGetCmpControllerRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCmpControllerRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCmpControllerRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCmpControllerRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCmpControllerRequestRequest.Merge(m, src)
}
func (m *QueryGetCmpControllerRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCmpControllerRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCmpControllerRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCmpControllerRequestRequest proto.InternalMessageInfo

func (m *QueryGetCmpControllerRequestRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetCmpControllerRequestResponse struct {
	CmpControllerRequest CmpControllerRequest `protobuf:"bytes,1,opt,name=cmpControllerRequest,proto3" json:"cmpControllerRequest"`
}

func (m *QueryGetCmpControllerRequestResponse) Reset()         { *m = QueryGetCmpControllerRequestResponse{} }
func (m *QueryGetCmpControllerRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCmpControllerRequestResponse) ProtoMessage()    {}
func (*QueryGetCmpControllerRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{7}
}
func (m *QueryGetCmpControllerRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCmpControllerRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCmpControllerRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCmpControllerRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCmpControllerRequestResponse.Merge(m, src)
}
func (m *QueryGetCmpControllerRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCmpControllerRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCmpControllerRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCmpControllerRequestResponse proto.InternalMessageInfo

func (m *QueryGetCmpControllerRequestResponse) GetCmpControllerRequest() CmpControllerRequest {
	if m != nil {
		return m.CmpControllerRequest
	}
	return CmpControllerRequest{}
}

type QueryAllCmpControllerRequestRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCmpControllerRequestRequest) Reset()         { *m = QueryAllCmpControllerRequestRequest{} }
func (m *QueryAllCmpControllerRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCmpControllerRequestRequest) ProtoMessage()    {}
func (*QueryAllCmpControllerRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{8}
}
func (m *QueryAllCmpControllerRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCmpControllerRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCmpControllerRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCmpControllerRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCmpControllerRequestRequest.Merge(m, src)
}
func (m *QueryAllCmpControllerRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCmpControllerRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCmpControllerRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCmpControllerRequestRequest proto.InternalMessageInfo

func (m *QueryAllCmpControllerRequestRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCmpControllerRequestResponse struct {
	CmpControllerRequest []CmpControllerRequest `protobuf:"bytes,1,rep,name=cmpControllerRequest,proto3" json:"cmpControllerRequest"`
	Pagination           *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCmpControllerRequestResponse) Reset()         { *m = QueryAllCmpControllerRequestResponse{} }
func (m *QueryAllCmpControllerRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCmpControllerRequestResponse) ProtoMessage()    {}
func (*QueryAllCmpControllerRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba3663865de3fd85, []int{9}
}
func (m *QueryAllCmpControllerRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCmpControllerRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCmpControllerRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCmpControllerRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCmpControllerRequestResponse.Merge(m, src)
}
func (m *QueryAllCmpControllerRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCmpControllerRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCmpControllerRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCmpControllerRequestResponse proto.InternalMessageInfo

func (m *QueryAllCmpControllerRequestResponse) GetCmpControllerRequest() []CmpControllerRequest {
	if m != nil {
		return m.CmpControllerRequest
	}
	return nil
}

func (m *QueryAllCmpControllerRequestResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.interchainaccounts.controller.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.interchainaccounts.controller.QueryParamsResponse")
	proto.RegisterType((*QueryGetCmpDataRequest)(nil), "cosmos.interchainaccounts.controller.QueryGetCmpDataRequest")
	proto.RegisterType((*QueryGetCmpDataResponse)(nil), "cosmos.interchainaccounts.controller.QueryGetCmpDataResponse")
	proto.RegisterType((*QueryAllCmpDataRequest)(nil), "cosmos.interchainaccounts.controller.QueryAllCmpDataRequest")
	proto.RegisterType((*QueryAllCmpDataResponse)(nil), "cosmos.interchainaccounts.controller.QueryAllCmpDataResponse")
	proto.RegisterType((*QueryGetCmpControllerRequestRequest)(nil), "cosmos.interchainaccounts.controller.QueryGetCmpControllerRequestRequest")
	proto.RegisterType((*QueryGetCmpControllerRequestResponse)(nil), "cosmos.interchainaccounts.controller.QueryGetCmpControllerRequestResponse")
	proto.RegisterType((*QueryAllCmpControllerRequestRequest)(nil), "cosmos.interchainaccounts.controller.QueryAllCmpControllerRequestRequest")
	proto.RegisterType((*QueryAllCmpControllerRequestResponse)(nil), "cosmos.interchainaccounts.controller.QueryAllCmpControllerRequestResponse")
}

func init() {
	proto.RegisterFile("interchainaccounts/controller/query.proto", fileDescriptor_ba3663865de3fd85)
}

var fileDescriptor_ba3663865de3fd85 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0xb6, 0xb4, 0x85, 0xe5, 0xb6, 0x44, 0x14, 0x45, 0xc8, 0x20, 0x53, 0xf1, 0xa7, 0xd6,
	0xab, 0x14, 0xa1, 0xfe, 0x40, 0x55, 0xb5, 0xa5, 0x44, 0xad, 0x54, 0xa9, 0xe4, 0xc8, 0xa5, 0x6c,
	0xdc, 0x95, 0x63, 0xc9, 0xf6, 0xba, 0xf6, 0x06, 0xb5, 0x42, 0x5c, 0x78, 0x02, 0x24, 0xae, 0xbc,
	0x04, 0x12, 0x4f, 0xc0, 0x01, 0x7a, 0xac, 0xc4, 0x85, 0x13, 0x42, 0x09, 0x3c, 0x03, 0x17, 0x0e,
	0x28, 0xbb, 0xe3, 0x26, 0xc1, 0xf9, 0x73, 0x1b, 0x6e, 0xb1, 0x3d, 0xf3, 0xfd, 0xcd, 0x7a, 0x1c,
	0x7c, 0xcf, 0x0d, 0x24, 0x8f, 0xec, 0x2a, 0x73, 0x03, 0x66, 0xdb, 0xa2, 0x16, 0xc8, 0x98, 0xda,
	0x22, 0x90, 0x91, 0xf0, 0x3c, 0x1e, 0xd1, 0x83, 0x1a, 0x8f, 0x8e, 0xac, 0x30, 0x12, 0x52, 0x90,
	0x19, 0x5b, 0xc4, 0xbe, 0x88, 0xad, 0x74, 0x87, 0xd5, 0xea, 0x28, 0xe4, 0x1d, 0xe1, 0x08, 0xd5,
	0x40, 0x9b, 0xbf, 0x74, 0x6f, 0xe1, 0xba, 0x23, 0x84, 0xe3, 0x71, 0xca, 0x42, 0x97, 0xb2, 0x20,
	0x10, 0x92, 0x49, 0x57, 0x04, 0x31, 0x3c, 0xbd, 0xaf, 0x91, 0x69, 0x85, 0xc5, 0x5c, 0x53, 0xd2,
	0x97, 0xc5, 0x0a, 0x97, 0xac, 0x48, 0x43, 0xe6, 0xb8, 0x81, 0x2a, 0x4e, 0x6a, 0xfb, 0x0b, 0x0e,
	0x59, 0xc4, 0xfc, 0x04, 0x77, 0xb6, 0x7f, 0xad, 0xed, 0x87, 0x7b, 0xfb, 0x4c, 0x32, 0xa8, 0x5e,
	0x1e, 0x5c, 0xdd, 0xba, 0xdc, 0x8b, 0xf8, 0x41, 0x8d, 0xc7, 0x52, 0xf7, 0x9a, 0x79, 0x4c, 0x9e,
	0x35, 0x75, 0xef, 0x2a, 0xfa, 0xb2, 0x7e, 0x66, 0x32, 0x7c, 0xa5, 0xe3, 0x6e, 0x1c, 0x8a, 0x20,
	0xe6, 0x64, 0x1b, 0x4f, 0x6a, 0x99, 0xd7, 0xd0, 0x4d, 0x74, 0xf7, 0xf2, 0xfc, 0xac, 0x35, 0x4c,
	0xb2, 0x96, 0x46, 0x59, 0xbf, 0x70, 0xfc, 0xfd, 0x46, 0xae, 0x0c, 0x08, 0xa6, 0x85, 0xaf, 0x2a,
	0x8a, 0x12, 0x97, 0x1b, 0x7e, 0xf8, 0x84, 0x49, 0x06, 0xe4, 0x24, 0x8f, 0x27, 0xdc, 0x60, 0x9f,
	0x1f, 0x2a, 0x92, 0x4b, 0x65, 0x7d, 0x61, 0x56, 0xf1, 0x74, 0xaa, 0x1e, 0x64, 0xed, 0xe0, 0x29,
	0x5b, 0xdf, 0x02, 0x5d, 0x73, 0xc3, 0xe9, 0x02, 0x1c, 0x10, 0x96, 0x60, 0x98, 0x2f, 0x40, 0xd9,
	0x9a, 0xe7, 0xfd, 0xa3, 0xec, 0x29, 0xc6, 0xad, 0xb1, 0x02, 0xd7, 0xed, 0x84, 0xab, 0x79, 0x06,
	0x2c, 0x7d, 0xec, 0xe0, 0x0c, 0x58, 0xbb, 0xcc, 0xe1, 0xd0, 0x5b, 0x6e, 0xeb, 0x34, 0x3f, 0x20,
	0x30, 0xd3, 0x4e, 0xd1, 0xcd, 0xcc, 0xf8, 0x79, 0xcd, 0x90, 0x52, 0x87, 0xe4, 0x31, 0x25, 0xf9,
	0xce, 0x40, 0xc9, 0x5a, 0x4b, 0x87, 0xe6, 0x47, 0xf8, 0x56, 0x5b, 0xfe, 0x1b, 0xa7, 0xc4, 0x89,
	0xbf, 0xbe, 0xc3, 0x7b, 0x8f, 0xf0, 0x4c, 0xff, 0x6e, 0x70, 0x2f, 0x71, 0xde, 0xee, 0xf2, 0x1c,
	0xb2, 0x5e, 0x1e, 0x3a, 0x8a, 0x14, 0x02, 0xe4, 0xd2, 0x15, 0xdd, 0xf4, 0xc1, 0x9b, 0x1e, 0x47,
	0x4f, 0x6f, 0xa3, 0x1a, 0xff, 0xaf, 0x24, 0x8d, 0x9e, 0x7c, 0x03, 0xd3, 0x18, 0xff, 0x7f, 0x69,
	0x8c, 0xec, 0xc8, 0xcc, 0x7f, 0xbe, 0x88, 0x27, 0x94, 0x4f, 0xf2, 0x11, 0xe1, 0x49, 0xbd, 0x05,
	0xc8, 0xe2, 0x70, 0xaa, 0xd3, 0x4b, 0xa9, 0xb0, 0x74, 0x86, 0x4e, 0xad, 0xca, 0x7c, 0xf8, 0xe6,
	0xeb, 0xcf, 0x77, 0x63, 0x94, 0xcc, 0x51, 0x58, 0xd8, 0x2d, 0x88, 0xb9, 0xde, 0xcb, 0x98, 0x7c,
	0x41, 0x78, 0x0a, 0xde, 0x2b, 0xf2, 0x38, 0x03, 0x7b, 0x6a, 0xa7, 0x15, 0x56, 0xce, 0xd8, 0x0d,
	0xfa, 0x57, 0x95, 0xfe, 0x25, 0xb2, 0x30, 0xa4, 0xfe, 0xe4, 0x03, 0x41, 0x5f, 0xa9, 0xf7, 0xef,
	0x35, 0xf9, 0x84, 0x30, 0x06, 0xd0, 0x35, 0xcf, 0xcb, 0x64, 0x26, 0xb5, 0x06, 0x33, 0x99, 0x49,
	0x6f, 0x38, 0x73, 0x41, 0x99, 0x29, 0x12, 0x9a, 0xd1, 0x0c, 0xf9, 0x83, 0x70, 0xbe, 0xdb, 0x69,
	0x26, 0x5b, 0x99, 0xd3, 0xed, 0xf5, 0x8e, 0x17, 0xb6, 0x47, 0x01, 0x05, 0x46, 0x77, 0x94, 0xd1,
	0x12, 0xd9, 0xcc, 0x60, 0x34, 0xfd, 0xa1, 0x3e, 0x9d, 0xe1, 0x6f, 0x84, 0xa7, 0xbb, 0xf1, 0x35,
	0x07, 0xba, 0x95, 0x79, 0x24, 0x23, 0x49, 0x60, 0xc0, 0x02, 0x33, 0x37, 0x55, 0x02, 0xab, 0x64,
	0xe5, 0x5c, 0x09, 0xac, 0x97, 0x8f, 0xeb, 0x06, 0x3a, 0xa9, 0x1b, 0xe8, 0x47, 0xdd, 0x40, 0x6f,
	0x1b, 0x46, 0xee, 0xa4, 0x61, 0xe4, 0xbe, 0x35, 0x8c, 0xdc, 0xf3, 0x45, 0xc7, 0x95, 0xd5, 0x5a,
	0xc5, 0xb2, 0x85, 0xdf, 0x8f, 0xe2, 0xb0, 0x9d, 0x44, 0x1e, 0x85, 0x3c, 0xae, 0x4c, 0xaa, 0xff,
	0x3f, 0x0f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x4b, 0x18, 0xe4, 0x48, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a CmpData by index.
	CmpData(ctx context.Context, in *QueryGetCmpDataRequest, opts ...grpc.CallOption) (*QueryGetCmpDataResponse, error)
	// Queries a list of CmpData items.
	CmpDataAll(ctx context.Context, in *QueryAllCmpDataRequest, opts ...grpc.CallOption) (*QueryAllCmpDataResponse, error)
	// Queries a CmpControllerRequest by index.
	CmpControllerRequest(ctx context.Context, in *QueryGetCmpControllerRequestRequest, opts ...grpc.CallOption) (*QueryGetCmpControllerRequestResponse, error)
	// Queries a list of CmpControllerRequest items.
	CmpControllerRequestAll(ctx context.Context, in *QueryAllCmpControllerRequestRequest, opts ...grpc.CallOption) (*QueryAllCmpControllerRequestResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.controller.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CmpData(ctx context.Context, in *QueryGetCmpDataRequest, opts ...grpc.CallOption) (*QueryGetCmpDataResponse, error) {
	out := new(QueryGetCmpDataResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.controller.Query/CmpData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CmpDataAll(ctx context.Context, in *QueryAllCmpDataRequest, opts ...grpc.CallOption) (*QueryAllCmpDataResponse, error) {
	out := new(QueryAllCmpDataResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.controller.Query/CmpDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CmpControllerRequest(ctx context.Context, in *QueryGetCmpControllerRequestRequest, opts ...grpc.CallOption) (*QueryGetCmpControllerRequestResponse, error) {
	out := new(QueryGetCmpControllerRequestResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.controller.Query/CmpControllerRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CmpControllerRequestAll(ctx context.Context, in *QueryAllCmpControllerRequestRequest, opts ...grpc.CallOption) (*QueryAllCmpControllerRequestResponse, error) {
	out := new(QueryAllCmpControllerRequestResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.controller.Query/CmpControllerRequestAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a CmpData by index.
	CmpData(context.Context, *QueryGetCmpDataRequest) (*QueryGetCmpDataResponse, error)
	// Queries a list of CmpData items.
	CmpDataAll(context.Context, *QueryAllCmpDataRequest) (*QueryAllCmpDataResponse, error)
	// Queries a CmpControllerRequest by index.
	CmpControllerRequest(context.Context, *QueryGetCmpControllerRequestRequest) (*QueryGetCmpControllerRequestResponse, error)
	// Queries a list of CmpControllerRequest items.
	CmpControllerRequestAll(context.Context, *QueryAllCmpControllerRequestRequest) (*QueryAllCmpControllerRequestResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CmpData(ctx context.Context, req *QueryGetCmpDataRequest) (*QueryGetCmpDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmpData not implemented")
}
func (*UnimplementedQueryServer) CmpDataAll(ctx context.Context, req *QueryAllCmpDataRequest) (*QueryAllCmpDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmpDataAll not implemented")
}
func (*UnimplementedQueryServer) CmpControllerRequest(ctx context.Context, req *QueryGetCmpControllerRequestRequest) (*QueryGetCmpControllerRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmpControllerRequest not implemented")
}
func (*UnimplementedQueryServer) CmpControllerRequestAll(ctx context.Context, req *QueryAllCmpControllerRequestRequest) (*QueryAllCmpControllerRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmpControllerRequestAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.controller.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CmpData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCmpDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CmpData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.controller.Query/CmpData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CmpData(ctx, req.(*QueryGetCmpDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CmpDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCmpDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CmpDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.controller.Query/CmpDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CmpDataAll(ctx, req.(*QueryAllCmpDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CmpControllerRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCmpControllerRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CmpControllerRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.controller.Query/CmpControllerRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CmpControllerRequest(ctx, req.(*QueryGetCmpControllerRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CmpControllerRequestAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCmpControllerRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CmpControllerRequestAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.controller.Query/CmpControllerRequestAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CmpControllerRequestAll(ctx, req.(*QueryAllCmpControllerRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.interchainaccounts.controller.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CmpData",
			Handler:    _Query_CmpData_Handler,
		},
		{
			MethodName: "CmpDataAll",
			Handler:    _Query_CmpDataAll_Handler,
		},
		{
			MethodName: "CmpControllerRequest",
			Handler:    _Query_CmpControllerRequest_Handler,
		},
		{
			MethodName: "CmpControllerRequestAll",
			Handler:    _Query_CmpControllerRequestAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchainaccounts/controller/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCmpDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCmpDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCmpDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCmpDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCmpDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCmpDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CmpData.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCmpDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCmpDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCmpDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCmpDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCmpDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCmpDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CmpData) > 0 {
		for iNdEx := len(m.CmpData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CmpData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCmpControllerRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCmpControllerRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCmpControllerRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCmpControllerRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCmpControllerRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCmpControllerRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CmpControllerRequest.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCmpControllerRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCmpControllerRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCmpControllerRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCmpControllerRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCmpControllerRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCmpControllerRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CmpControllerRequest) > 0 {
		for iNdEx := len(m.CmpControllerRequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CmpControllerRequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCmpDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCmpDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CmpData.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCmpDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCmpDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CmpData) > 0 {
		for _, e := range m.CmpData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCmpControllerRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCmpControllerRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CmpControllerRequest.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCmpControllerRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCmpControllerRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CmpControllerRequest) > 0 {
		for _, e := range m.CmpControllerRequest {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCmpDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCmpDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCmpDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCmpDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCmpDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCmpDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmpData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CmpData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCmpDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCmpDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCmpDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCmpDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCmpDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCmpDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmpData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CmpData = append(m.CmpData, CmpData{})
			if err := m.CmpData[len(m.CmpData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCmpControllerRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCmpControllerRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCmpControllerRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCmpControllerRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCmpControllerRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCmpControllerRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmpControllerRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CmpControllerRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCmpControllerRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCmpControllerRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCmpControllerRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCmpControllerRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCmpControllerRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCmpControllerRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmpControllerRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CmpControllerRequest = append(m.CmpControllerRequest, CmpControllerRequest{})
			if err := m.CmpControllerRequest[len(m.CmpControllerRequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
