#!/bin/bash

# set -x

if [[ $1 = "--h" || $1 = "-h" || $1 = "--help" || -z $1 ]]; then
  echo "Usage: $0 COSMOS_ADDRESS CHAIN_ID ITEM PRICE"
  echo "  Example: $0 cosmos1m9l358xunhhwds0568za49mzhvuxx9uxre5tud test-1 test.com 140 (140 means 140 stakes)"
  exit 0
fi

CONT_ID=$(docker ps | grep test-1 | sed -e 's/\s.*$//')

ADDRESS=$1
CHAIN=$2
ITEM=$3
PRICE=$4
NODE=tcp://chain-test-1:16657

if [[ -z "${CHAIN}" ]]; then
  CHAIN=test-1
fi

if [[ "${CHAIN}" = "test-1" ]]; then
  NODE=tcp://chain-test-1:16657
fi

if [[ "${CHAIN}" = "test-3" ]]; then
  NODE=tcp://chain-test-3:36657
fi

ICA=$(docker exec $CONT_ID icad query intertx interchainaccounts connection-0 $ADDRESS --home ./data/$CHAIN --node $NODE -o json 2> /dev/null | jq -r '.interchain_account_address') 
if [[ -z "$ICA" ]]; then
  echo "Error: No interchain account found"
  exit 1
fi

docker exec $CONT_ID icad tx controller submit-tx "{
    \"@type\":\"/cosmos.interchainaccounts.nameservice.MsgCmpBuy\",
    \"creator\": \"$ICA\",
    \"name\":\"$ITEM\",
    \"bid\":\"$PRICE\",
    \"metadata\":\"test\"
}" connection-0 --from $ADDRESS --chain-id $CHAIN --home ./data/$CHAIN --node $NODE --keyring-backend test -y 1>/dev/null 2>&1

echo "Buy transaction sent. Check the result in a few seconds." 1>/dev/null 2>&1

sleep 5
cd ..
python3 scripts/query_status.py -r "$ITEM:::$ICA" -w $ADDRESS -ica $ICA -c $CHAIN
