#!/bin/bash

# set -x

if [[ $1 = "--h" || $1 = "-h" || $1 = "--help" || -z $1 ]]; then
  echo "Usage: $0 COSMOS_ADDRESS CHAIN_ID"
  echo "  Register an interchain account for COSMOS_ADDRESS on chain CHAIN_ID and fund it with 100,000stake"
  echo "  Example: $0 cosmos1m9l358xunhhwds0568za49mzhvuxx9uxre5tud test-1"
  exit 0
fi

cd $HOME/interopera/interchain-accounts-demo

CONT_ID=$(docker ps | grep test-1 | sed -e 's/\s.*$//')

ADDRESS=$1
CHAIN=$2
NODE=tcp://chain-test-1:16657

if [[ -z "${CHAIN}" ]]; then
  CHAIN=test-1
fi

if [[ "${CHAIN}" = "test-1" ]]; then
  NODE=tcp://chain-test-1:16657
fi

if [[ "${CHAIN}" = "test-3" ]]; then
  NODE=tcp://chain-test-3:36657
fi

if docker exec $CONT_ID icad tx intertx register --from $ADDRESS --connection-id connection-0 --chain-id $CHAIN --home ./data/$CHAIN --node $NODE --keyring-backend test --timeout-height 1000 -y 1> /dev/null 2>&1; then
  :
else
  echo "Error: Register tx failed" >&2
  exit 2
fi

if [[ $? -ne 0 ]]; then
  echo "Failed to register interchain account for $ADDRESS" >&2
  exit 3
fi

declare -i i=0

for i in {1..10}
do
  echo -n . >&2
  if [[ $i -eq 10 ]]; then
    break
  fi

  ICA=$(docker exec $CONT_ID icad query intertx interchainaccounts connection-0 $ADDRESS --home ./data/$CHAIN --node $NODE -o json 2> /dev/null | jq -r '.interchain_account_address') 
  if [[ -n "$ICA" ]]; then
    break
  fi

  sleep 2
done

echo >&2
if [[ $i -eq 10 ]]; then
  echo "Failed to register interchain account. Try restarting relayer" >&2
  exit 4
else
  echo "Interchain account created: " >&2
  echo $ICA
  docker exec $CONT_ID icad tx bank send $WALLET_3 $ICA 100000stake --chain-id test-2 --home ./data/test-2 --keyring-backend test -y 1> /dev/null 2>&1
  exit 0
fi
