#!/bin/bash

# set -x

if [[ $1 = "--h" || $1 = "-h" || $1 = "--help" || -z $1 ]]; then
  echo "Usage: $0 COSMOS_ADDRESS CHAIN_ID"
  echo "  Register an interchain account for COSMOS_ADDRESS on chain CHAIN_ID and fund it with 100,000stake"
  echo "  Example: $0 cosmos1m9l358xunhhwds0568za49mzhvuxx9uxre5tud test-1"
  exit 0
fi

ADDRESS=$1
CHAIN=$2
NODE=tcp://localhost:16657

if [[ -z "${CHAIN}" ]]; then
  CHAIN=test-1
fi

if [[ "${CHAIN}" = "test-1" ]]; then
  NODE=tcp://localhost:16657
fi

if [[ "${CHAIN}" = "test-3" ]]; then
  NODE=tcp://localhost:36657
fi

icad tx intertx register --from $ADDRESS --connection-id connection-0 --chain-id $CHAIN --home ./data/$CHAIN --node $NODE --keyring-backend test --timeout-height 1000 -y 1> /dev/null 2>&1

if [[ $? -ne 0 ]]; then
  echo "Failed to register interchain account for $ADDRESS"
  exit 1
fi

declare -i i=0

for i in {1..10}
do
  echo -n . 
  if [[ $i -eq 10 ]]; then
    break
  fi

  ICA=$(icad query intertx interchainaccounts connection-0 $ADDRESS --home ./data/$CHAIN --node $NODE -o json 2> /dev/null | jq -r '.interchain_account_address') 
  if [[ -n "$ICA" ]]; then
    break
  fi

  sleep 2
done

echo
if [[ $i -eq 10 ]]; then
  echo "Failed to register interchain account. Try restarting relayer" >&2
else
  echo "Interchain account created: $ICA"
  icad tx bank send $WALLET_3 $ICA 100000stake --chain-id test-2 --home ./data/test-2 --keyring-backend test -y
fi
