// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchainaccounts/cmp/account_address.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AccountAddress struct {
	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender    string `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthYear uint64 `protobuf:"varint,4,opt,name=birthYear,proto3" json:"birthYear,omitempty"`
	Creator   string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *AccountAddress) Reset()         { *m = AccountAddress{} }
func (m *AccountAddress) String() string { return proto.CompactTextString(m) }
func (*AccountAddress) ProtoMessage()    {}
func (*AccountAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f69c6f1fc75136aa, []int{0}
}
func (m *AccountAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAddress.Merge(m, src)
}
func (m *AccountAddress) XXX_Size() int {
	return m.Size()
}
func (m *AccountAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAddress.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAddress proto.InternalMessageInfo

func (m *AccountAddress) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *AccountAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountAddress) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AccountAddress) GetBirthYear() uint64 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

func (m *AccountAddress) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountAddress)(nil), "cosmos.interchainaccounts.cmp.AccountAddress")
}

func init() {
	proto.RegisterFile("interchainaccounts/cmp/account_address.proto", fileDescriptor_f69c6f1fc75136aa)
}

var fileDescriptor_f69c6f1fc75136aa = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x48, 0x8b, 0xea, 0x81, 0xc1, 0x42, 0xc8, 0x03, 0x58, 0x15, 0x53, 0x07, 0x48,
	0x84, 0x78, 0x82, 0xb2, 0xb2, 0x75, 0x83, 0x05, 0x39, 0x97, 0x53, 0xe3, 0xc1, 0x76, 0x74, 0x76,
	0xa5, 0xf2, 0x0a, 0x4c, 0x3c, 0x16, 0x63, 0x47, 0x46, 0x94, 0xbc, 0x08, 0x92, 0x5d, 0xc8, 0xc0,
	0x76, 0xdf, 0x27, 0xfd, 0xc3, 0x77, 0xfc, 0xd6, 0xb8, 0x88, 0x04, 0x9d, 0x36, 0x4e, 0x03, 0xf8,
	0x9d, 0x8b, 0xa1, 0x06, 0xdb, 0xd7, 0x47, 0x78, 0xd5, 0x6d, 0x4b, 0x18, 0x42, 0xd5, 0x93, 0x8f,
	0x5e, 0x5c, 0x83, 0x0f, 0xd6, 0x87, 0xea, 0xff, 0xa8, 0x02, 0xdb, 0xdf, 0xbc, 0x33, 0x7e, 0xbe,
	0xce, 0x62, 0x9d, 0x77, 0xe2, 0x82, 0xcf, 0x8c, 0x6b, 0x71, 0x2f, 0xd9, 0x92, 0xad, 0x16, 0x9b,
	0x0c, 0x42, 0xf0, 0xd2, 0x69, 0x8b, 0xf2, 0x24, 0xc9, 0x74, 0x8b, 0x4b, 0x3e, 0xdf, 0xa2, 0x6b,
	0x91, 0xe4, 0x69, 0xb2, 0x47, 0x12, 0x57, 0x7c, 0xd1, 0x18, 0x8a, 0xdd, 0x33, 0x6a, 0x92, 0xe5,
	0x92, 0xad, 0xca, 0xcd, 0x24, 0x84, 0xe4, 0x67, 0x40, 0xa8, 0xa3, 0x27, 0x39, 0x4b, 0xb3, 0x5f,
	0x7c, 0x7c, 0xfa, 0x1c, 0x14, 0x3b, 0x0c, 0x8a, 0x7d, 0x0f, 0x8a, 0x7d, 0x8c, 0xaa, 0x38, 0x8c,
	0xaa, 0xf8, 0x1a, 0x55, 0xf1, 0x72, 0xbf, 0x35, 0xb1, 0xdb, 0x35, 0x15, 0x78, 0x5b, 0xe7, 0xa0,
	0x7a, 0x0a, 0xba, 0xfb, 0x7b, 0xc3, 0x3e, 0x3d, 0x22, 0xbe, 0xf5, 0x18, 0x9a, 0x79, 0xea, 0x7f,
	0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xc4, 0x15, 0xf5, 0x2f, 0x01, 0x00, 0x00,
}

func (m *AccountAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAccountAddress(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BirthYear != 0 {
		i = encodeVarintAccountAddress(dAtA, i, uint64(m.BirthYear))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Gender) > 0 {
		i -= len(m.Gender)
		copy(dAtA[i:], m.Gender)
		i = encodeVarintAccountAddress(dAtA, i, uint64(len(m.Gender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAccountAddress(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintAccountAddress(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAccountAddress(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccountAddress(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccountAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovAccountAddress(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAccountAddress(uint64(l))
	}
	l = len(m.Gender)
	if l > 0 {
		n += 1 + l + sovAccountAddress(uint64(l))
	}
	if m.BirthYear != 0 {
		n += 1 + sovAccountAddress(uint64(m.BirthYear))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAccountAddress(uint64(l))
	}
	return n
}

func sovAccountAddress(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccountAddress(x uint64) (n int) {
	return sovAccountAddress(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccountAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccountAddress
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccountAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccountAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccountAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccountAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccountAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccountAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BirthYear", wireType)
			}
			m.BirthYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BirthYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccountAddress
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccountAddress
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccountAddress(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccountAddress
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccountAddress(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccountAddress
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccountAddress
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccountAddress
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccountAddress
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccountAddress
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccountAddress        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccountAddress          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccountAddress = fmt.Errorf("proto: unexpected end of group")
)
