// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchainaccounts/cmp/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateAccountAddress struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index     string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender    string `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthYear uint64 `protobuf:"varint,5,opt,name=birthYear,proto3" json:"birthYear,omitempty"`
}

func (m *MsgCreateAccountAddress) Reset()         { *m = MsgCreateAccountAddress{} }
func (m *MsgCreateAccountAddress) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAccountAddress) ProtoMessage()    {}
func (*MsgCreateAccountAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{0}
}
func (m *MsgCreateAccountAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAccountAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAccountAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAccountAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAccountAddress.Merge(m, src)
}
func (m *MsgCreateAccountAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAccountAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAccountAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAccountAddress proto.InternalMessageInfo

func (m *MsgCreateAccountAddress) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateAccountAddress) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgCreateAccountAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateAccountAddress) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *MsgCreateAccountAddress) GetBirthYear() uint64 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

type MsgCreateAccountAddressResponse struct {
}

func (m *MsgCreateAccountAddressResponse) Reset()         { *m = MsgCreateAccountAddressResponse{} }
func (m *MsgCreateAccountAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAccountAddressResponse) ProtoMessage()    {}
func (*MsgCreateAccountAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{1}
}
func (m *MsgCreateAccountAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAccountAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAccountAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAccountAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAccountAddressResponse.Merge(m, src)
}
func (m *MsgCreateAccountAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAccountAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAccountAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAccountAddressResponse proto.InternalMessageInfo

type MsgUpdateAccountAddress struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index     string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender    string `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthYear uint64 `protobuf:"varint,5,opt,name=birthYear,proto3" json:"birthYear,omitempty"`
}

func (m *MsgUpdateAccountAddress) Reset()         { *m = MsgUpdateAccountAddress{} }
func (m *MsgUpdateAccountAddress) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAccountAddress) ProtoMessage()    {}
func (*MsgUpdateAccountAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{2}
}
func (m *MsgUpdateAccountAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAccountAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAccountAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAccountAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAccountAddress.Merge(m, src)
}
func (m *MsgUpdateAccountAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAccountAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAccountAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAccountAddress proto.InternalMessageInfo

func (m *MsgUpdateAccountAddress) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateAccountAddress) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgUpdateAccountAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateAccountAddress) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *MsgUpdateAccountAddress) GetBirthYear() uint64 {
	if m != nil {
		return m.BirthYear
	}
	return 0
}

type MsgUpdateAccountAddressResponse struct {
}

func (m *MsgUpdateAccountAddressResponse) Reset()         { *m = MsgUpdateAccountAddressResponse{} }
func (m *MsgUpdateAccountAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAccountAddressResponse) ProtoMessage()    {}
func (*MsgUpdateAccountAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{3}
}
func (m *MsgUpdateAccountAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAccountAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAccountAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAccountAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAccountAddressResponse.Merge(m, src)
}
func (m *MsgUpdateAccountAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAccountAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAccountAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAccountAddressResponse proto.InternalMessageInfo

type MsgDeleteAccountAddress struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Index   string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *MsgDeleteAccountAddress) Reset()         { *m = MsgDeleteAccountAddress{} }
func (m *MsgDeleteAccountAddress) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAccountAddress) ProtoMessage()    {}
func (*MsgDeleteAccountAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{4}
}
func (m *MsgDeleteAccountAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAccountAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAccountAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAccountAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAccountAddress.Merge(m, src)
}
func (m *MsgDeleteAccountAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAccountAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAccountAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAccountAddress proto.InternalMessageInfo

func (m *MsgDeleteAccountAddress) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteAccountAddress) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type MsgDeleteAccountAddressResponse struct {
}

func (m *MsgDeleteAccountAddressResponse) Reset()         { *m = MsgDeleteAccountAddressResponse{} }
func (m *MsgDeleteAccountAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAccountAddressResponse) ProtoMessage()    {}
func (*MsgDeleteAccountAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62c479b01165c4de, []int{5}
}
func (m *MsgDeleteAccountAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAccountAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAccountAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAccountAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAccountAddressResponse.Merge(m, src)
}
func (m *MsgDeleteAccountAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAccountAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAccountAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAccountAddressResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateAccountAddress)(nil), "cosmos.interchainaccounts.cmp.MsgCreateAccountAddress")
	proto.RegisterType((*MsgCreateAccountAddressResponse)(nil), "cosmos.interchainaccounts.cmp.MsgCreateAccountAddressResponse")
	proto.RegisterType((*MsgUpdateAccountAddress)(nil), "cosmos.interchainaccounts.cmp.MsgUpdateAccountAddress")
	proto.RegisterType((*MsgUpdateAccountAddressResponse)(nil), "cosmos.interchainaccounts.cmp.MsgUpdateAccountAddressResponse")
	proto.RegisterType((*MsgDeleteAccountAddress)(nil), "cosmos.interchainaccounts.cmp.MsgDeleteAccountAddress")
	proto.RegisterType((*MsgDeleteAccountAddressResponse)(nil), "cosmos.interchainaccounts.cmp.MsgDeleteAccountAddressResponse")
}

func init() { proto.RegisterFile("interchainaccounts/cmp/tx.proto", fileDescriptor_62c479b01165c4de) }

var fileDescriptor_62c479b01165c4de = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x1b, 0xfb, 0x47, 0x9a, 0x31, 0x14, 0x3d, 0x8a, 0x5e, 0x6b, 0xa7, 0x0e, 0x7a, 0x87,
	0x0a, 0x8e, 0x42, 0xd5, 0x45, 0xa4, 0x4b, 0xc1, 0x41, 0x17, 0xb9, 0xe6, 0x5e, 0xae, 0x07, 0x5e,
	0x12, 0x92, 0x14, 0xea, 0x97, 0x10, 0xc1, 0x2f, 0xe3, 0x47, 0x70, 0xec, 0xe8, 0x28, 0xed, 0x17,
	0x11, 0x93, 0x5e, 0x3b, 0x98, 0x96, 0x43, 0x17, 0xb7, 0x7b, 0x1f, 0xde, 0x27, 0xcf, 0x0f, 0x9e,
	0x4b, 0x70, 0x2b, 0x65, 0x1a, 0x24, 0x1d, 0x45, 0x29, 0x8b, 0x28, 0xe5, 0x63, 0xa6, 0x55, 0x48,
	0x33, 0x11, 0xea, 0x49, 0x20, 0x24, 0xd7, 0x9c, 0xec, 0x53, 0xae, 0x32, 0xae, 0x82, 0x9f, 0x7b,
	0x01, 0xcd, 0x44, 0xf3, 0x70, 0x8d, 0x7f, 0x31, 0x3c, 0x44, 0x71, 0x2c, 0x41, 0x29, 0x7b, 0x58,
	0xe7, 0x15, 0xe1, 0xdd, 0xbe, 0x4a, 0x2e, 0x25, 0x44, 0x1a, 0x7a, 0x76, 0xa5, 0x67, 0x37, 0x88,
	0x87, 0xb7, 0xe9, 0xb7, 0xce, 0xa5, 0x87, 0xda, 0xa8, 0x5b, 0x1f, 0xe4, 0x23, 0x69, 0xe0, 0x6a,
	0xca, 0x62, 0x98, 0x78, 0x5b, 0x46, 0xb7, 0x03, 0x21, 0xb8, 0xc2, 0xa2, 0x0c, 0xbc, 0xb2, 0x11,
	0xcd, 0x37, 0xd9, 0xc1, 0xb5, 0x04, 0x58, 0x0c, 0xd2, 0xab, 0x18, 0x75, 0x31, 0x91, 0x3d, 0x5c,
	0x1f, 0xa6, 0x52, 0x8f, 0xee, 0x20, 0x92, 0x5e, 0xb5, 0x8d, 0xba, 0x95, 0xc1, 0x4a, 0xe8, 0x1c,
	0xe0, 0xd6, 0x1a, 0xa8, 0x01, 0x28, 0xc1, 0x99, 0x82, 0x1c, 0xfc, 0x56, 0xc4, 0xff, 0x0f, 0xdc,
	0x05, 0xb5, 0x04, 0xbf, 0x36, 0xdc, 0x57, 0xf0, 0x08, 0x7f, 0xe5, 0x5e, 0xa4, 0xb9, 0x8e, 0xca,
	0xd3, 0x4e, 0xde, 0xca, 0xb8, 0xdc, 0x57, 0x09, 0x79, 0x46, 0xb8, 0xe1, 0x2c, 0xf9, 0x2c, 0xd8,
	0xf8, 0x3b, 0x05, 0x6b, 0x7a, 0x68, 0x9e, 0xff, 0xce, 0x97, 0x83, 0x19, 0x20, 0x67, 0x79, 0x05,
	0x80, 0x5c, 0xbe, 0x22, 0x40, 0x9b, 0x7a, 0x31, 0x40, 0xce, 0x56, 0x0a, 0x00, 0xb9, 0x7c, 0x45,
	0x80, 0x36, 0x55, 0x77, 0x71, 0xf3, 0x3e, 0xf3, 0xd1, 0x74, 0xe6, 0xa3, 0xcf, 0x99, 0x8f, 0x5e,
	0xe6, 0x7e, 0x69, 0x3a, 0xf7, 0x4b, 0x1f, 0x73, 0xbf, 0x74, 0x7f, 0x9c, 0xa4, 0x7a, 0x34, 0x1e,
	0x06, 0x94, 0x67, 0xa1, 0xcd, 0x08, 0x57, 0x19, 0x47, 0xcb, 0x5b, 0x3f, 0xb1, 0xef, 0xc6, 0x93,
	0x00, 0x35, 0xac, 0x99, 0xeb, 0x7e, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xd1, 0x9e, 0xde,
	0x5e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAccountAddress(ctx context.Context, in *MsgCreateAccountAddress, opts ...grpc.CallOption) (*MsgCreateAccountAddressResponse, error)
	UpdateAccountAddress(ctx context.Context, in *MsgUpdateAccountAddress, opts ...grpc.CallOption) (*MsgUpdateAccountAddressResponse, error)
	DeleteAccountAddress(ctx context.Context, in *MsgDeleteAccountAddress, opts ...grpc.CallOption) (*MsgDeleteAccountAddressResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAccountAddress(ctx context.Context, in *MsgCreateAccountAddress, opts ...grpc.CallOption) (*MsgCreateAccountAddressResponse, error) {
	out := new(MsgCreateAccountAddressResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.cmp.Msg/CreateAccountAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAccountAddress(ctx context.Context, in *MsgUpdateAccountAddress, opts ...grpc.CallOption) (*MsgUpdateAccountAddressResponse, error) {
	out := new(MsgUpdateAccountAddressResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.cmp.Msg/UpdateAccountAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteAccountAddress(ctx context.Context, in *MsgDeleteAccountAddress, opts ...grpc.CallOption) (*MsgDeleteAccountAddressResponse, error) {
	out := new(MsgDeleteAccountAddressResponse)
	err := c.cc.Invoke(ctx, "/cosmos.interchainaccounts.cmp.Msg/DeleteAccountAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAccountAddress(context.Context, *MsgCreateAccountAddress) (*MsgCreateAccountAddressResponse, error)
	UpdateAccountAddress(context.Context, *MsgUpdateAccountAddress) (*MsgUpdateAccountAddressResponse, error)
	DeleteAccountAddress(context.Context, *MsgDeleteAccountAddress) (*MsgDeleteAccountAddressResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAccountAddress(ctx context.Context, req *MsgCreateAccountAddress) (*MsgCreateAccountAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountAddress not implemented")
}
func (*UnimplementedMsgServer) UpdateAccountAddress(ctx context.Context, req *MsgUpdateAccountAddress) (*MsgUpdateAccountAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountAddress not implemented")
}
func (*UnimplementedMsgServer) DeleteAccountAddress(ctx context.Context, req *MsgDeleteAccountAddress) (*MsgDeleteAccountAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountAddress not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAccountAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAccountAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAccountAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.cmp.Msg/CreateAccountAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAccountAddress(ctx, req.(*MsgCreateAccountAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAccountAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAccountAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAccountAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.cmp.Msg/UpdateAccountAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAccountAddress(ctx, req.(*MsgUpdateAccountAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteAccountAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteAccountAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteAccountAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.interchainaccounts.cmp.Msg/DeleteAccountAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteAccountAddress(ctx, req.(*MsgDeleteAccountAddress))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.interchainaccounts.cmp.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountAddress",
			Handler:    _Msg_CreateAccountAddress_Handler,
		},
		{
			MethodName: "UpdateAccountAddress",
			Handler:    _Msg_UpdateAccountAddress_Handler,
		},
		{
			MethodName: "DeleteAccountAddress",
			Handler:    _Msg_DeleteAccountAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchainaccounts/cmp/tx.proto",
}

func (m *MsgCreateAccountAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAccountAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAccountAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BirthYear != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BirthYear))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Gender) > 0 {
		i -= len(m.Gender)
		copy(dAtA[i:], m.Gender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Gender)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAccountAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAccountAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAccountAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAccountAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAccountAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAccountAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BirthYear != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BirthYear))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Gender) > 0 {
		i -= len(m.Gender)
		copy(dAtA[i:], m.Gender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Gender)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAccountAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAccountAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAccountAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAccountAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAccountAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAccountAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAccountAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAccountAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAccountAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateAccountAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Gender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BirthYear != 0 {
		n += 1 + sovTx(uint64(m.BirthYear))
	}
	return n
}

func (m *MsgCreateAccountAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAccountAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Gender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BirthYear != 0 {
		n += 1 + sovTx(uint64(m.BirthYear))
	}
	return n
}

func (m *MsgUpdateAccountAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteAccountAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteAccountAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateAccountAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAccountAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAccountAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BirthYear", wireType)
			}
			m.BirthYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BirthYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAccountAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAccountAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAccountAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAccountAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAccountAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAccountAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BirthYear", wireType)
			}
			m.BirthYear = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BirthYear |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAccountAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAccountAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAccountAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAccountAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAccountAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAccountAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAccountAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAccountAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAccountAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
